### PR TITLE
added ts parsing for jest-editor-support

### PR DESCRIPTION
**Pull request by bookman25**
Creating this PR for discussion about the TypeScript file parsing.  I think we could actually replace babylon completely with typescript (it can do *.ts and *.js files).  And the nice thing about the npm typescript package is it's self-contained (no other dependencies).

I pulled the parser logic for both JS/TS into separate files and left TestFileParser.js to be just a thin wrapper.

### CODE REVIEW

**Comment by orta** [comment]
Interesting, this looks solid - I wonder if the typescript parser would handle flow functions in JS?

Other than that, yeah, I think it might be very reasonable to move to a TypeScript based parser! :D

**Comment by bookman25** [comment]
I'm not that familiar with flow, but I think I've added a flow function to test.  From what I can tell, the signature for flow functions and TypeScript functions is the same.  So I think it should be ok.

**Comment by orta** [comment]
For method declarations yep!

But I can think of a thing or two unique in Flow which might cause it to have a problem -  for example there is this:

```
import type {Thing} from './Types'
```

Hrm, though that doesn't seem to ever be used in the Jest test suite, nor any of my own. So perhaps it's worth it

**Comment by bookman25** [comment]
If we run into issues, we might be able to just strip flow type information from the file before running the parser.  One option might be: https://github.com/leebyron/flow-remove-types (but I'd wait to add until we actually run into issues).

**Comment by orta** [comment]
Agree! Want to remove babylon? 

With that, I'm happy to get this merged. Ideally before Wednesday otherwise I'll get it merged in manually - I'm working down at FB UK to get `jest-editor-support` merged into Jest mainline then 👍

**Comment by bookman25** [comment]
So I'm just exporting the parse function now.  It has properties for itBlocks/expects as part of it's return.  It's also a synchronous function call.

So in extension.ts where we call `await parser.run` will now store the data returned from the parse call `const data = parse(editor.document.uri.fsPath)` and each editor will be responsible for implementing the `expectAtLine` call.

**Comment by orta** [comment]
👍

**Comment by orta** [comment]
Awesome, it'll take a bit to get into the extension, but should hopefully happen this week 👍

**Pull request merged**
